### ISSUE TITLE
Failed to activate the transient-emacs package

### ISSUE THREAD

**Issue by morgoth** [yasuyuky/transient-emacs#642]
After last update, I'm getting error:
(atom version: 1.60.0)

```
/home/wojtek/.atom/packages/transient-emacs/node_modules/clipboardy/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import process from 'node:process';
                                                                                                                                                           ^^^^^^
SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (/usr/share/atom/resources/app/static/<embedded>:11:148836)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149690)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (/home/wojtek/.atom/packages/transient-emacs/lib/atom/main.js:6:20)
    at Object.<anonymous> (/home/wojtek/.atom/packages/transient-emacs/lib/atom/main.js:289:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (/home/wojtek/.atom/packages/transient-emacs/lib/entrypoint.js:4:20)
    at Object.<anonymous> (/home/wojtek/.atom/packages/transient-emacs/lib/entrypoint.js:7:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1175133)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3421427)
```

**Comment by yasuyuky** [comment]
Thanks for the feedback.
[For a while atom.io has been sluggish and unable to upload package upgrades and fixes for atom.](https://github.com/atom/atom/issues/25438)
And as mentioned in the said Issue, [GitHub has decided to sunset Atom.](https://github.blog/2022-06-08-sunsetting-atom/)
This package will also be phasing out support for Atom.
Unfortunately, this is out of my control.

There are two options left.
The first option is to clone this package and package it yourself using apm so you can continue to use it with Atom.
Or you can migrate your editor to VS Code.

I personally recommend the latter. The usability of both is similar and you can continue to use this package!
